Restaurant_DotnetCoreMvc/Models/Category.cs
namespace Restaurant_DotnetCoreMvc.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }


    }
}

Restaurant_DotnetCoreMvc/Models/ErrorViewModel.cs
using System;

namespace Restaurant_DotnetCoreMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Restaurant_DotnetCoreMvc/Models/MyDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Restaurant_DotnetCoreMvc.Models
{
    public class MyDbContext:DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        {
        }

        public DbSet<Pie> Pies { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ShopingCardItem> ShopingCards { get; set; }

    }
}

Restaurant_DotnetCoreMvc/Models/Pie.cs
namespace Restaurant_DotnetCoreMvc.Models
{
    public class Pie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumbnailUrl { get; set; }
        public bool IsPieOfTheWeek { get; set; }
        public Category Category { get; set; }

    }
}

Restaurant_DotnetCoreMvc/Models/ShopingCardItem.cs
namespace Restaurant_DotnetCoreMvc.Models
{
    public class ShopingCardItem
    {
        public int ShopingCardItemId { get; set; }
        public Pie Pie { get; set; }

        public string Amount { get; set; }

        public string ShopingCardId { get; set; }

    }
}

Restaurant_DotnetCoreMvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Restaurant_DotnetCoreMvc.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurant_DotnetCoreMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Restaurant_DotnetCoreMvc/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant_DotnetCoreMvc.Models;

namespace Restaurant_DotnetCoreMvc.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository pierepository;
        private readonly ICategoryRepository categoryrepository;

        public IActionResult Index()
        {
            return View("List", pierepository.AllPies);
        }

        public PieController(IPieRepository pierepository, ICategoryRepository categoryrepository)
        {
            this.pierepository = pierepository;
            this.categoryrepository = categoryrepository;
        }

        public ViewResult List() {
            ViewBag.Category = "New Category";
            return View(pierepository.AllPies);
        }

        [HttpPost]
        public IActionResult Create(Pie p) {

            pierepository.CreatePie(p);
            return RedirectToAction("Index");
        }
        public IActionResult Create()
        {
            return View("Create");
        }


        public IActionResult Details(int Id) { 
        
            var pie= pierepository.GetPieById(Id);
            if (pie == null)
                return NotFound();

            return View(pie);
        }

    }
}

Restaurant_DotnetCoreMvc/Controllers/ShopingCardsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Restaurant_DotnetCoreMvc.Models;

namespace Restaurant_DotnetCoreMvc.Controllers
{
    public class ShopingCardsController : Controller
    {
        private readonly IPieRepository _pierepository;
        private readonly IShopingCardsRepository _shopingcardsrepository;

        public ShopingCardsController(IPieRepository pierepository, IShopingCardsRepository shopingcardsrepository)
        {
            _shopingcardsrepository=shopingcardsrepository;
            _pierepository = pierepository;
        }
        public IActionResult Index()
        {
            return View("Index", _shopingcardsrepository.ShopingCards);
        }

        public ActionResult Create(int id)
        {
            try
            {
                _shopingcardsrepository.AddToShopingCard(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                _shopingcardsrepository.RemoveFromShopingCard(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public IActionResult TotalShopingCards() {

            return View(_shopingcardsrepository.TotalOfShopingCards());
        }

    }
}

Restaurant_DotnetCoreMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Restaurant_DotnetCoreMvc/Views/Pie/Create.cshtml
@model Pie
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="Pie" asp-action="Create" method="Post">
  <div class="form-group">
    <label for="formGroupExampleInput">Name</label>
    <input type="text" asp-for="Name" class="form-control" id="formGroupExampleInput" placeholder="Example input">
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Description</label>
    <input type="text" asp-for="Description" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
  </div>  <div class="form-group">
    <label for="formGroupExampleInput">Price</label>
    <input type="text" asp-for="Price" class="form-control" id="formGroupExampleInput" placeholder="Example input">
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
</form>

Restaurant_DotnetCoreMvc/Views/Pie/Details.cshtml
@model Pie
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<ul>
    <li>@Model.Name</li>
    <li>@Model.Description</li>
    <li>@Model.Category.CategoryName</li>
    <li>@Model.Price</li>
</ul>

Restaurant_DotnetCoreMvc/Views/Pie/List.cshtml
@model IEnumerable<Pie>

<h3>@ViewBag.Category</h3>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 img-fluid" src="https://media.istockphoto.com/photos/empty-restaurant-interior-picture-id1288064106?b=1&k=20&m=1288064106&s=170667a&w=0&h=hLfSBeMPduZyld4su0c3ju-yMPGOouuk_3Gzv7S4Jwo=" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 img-fluid" src="https://media.istockphoto.com/photos/empty-restaurant-interior-picture-id1290237592?b=1&k=20&m=1290237592&s=170667a&w=0&h=fgXWrrQ7qWpbiO8O_dpEVlS4JsTZYH8e3FoZ4UeoQH8=" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 img-fluid" src="https://media.istockphoto.com/photos/sacrificed-a-lot-for-this-startup-to-come-true-picture-id1303648971?b=1&k=20&m=1303648971&s=170667a&w=0&h=75SWYZMDFAzCZ7PvVjKJJW6ABvR7U2MJupml1yRtJMo=" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">
  <div class="row">
        @foreach (var item in @Model)
        {
              <div class="col-md-4 my-4">
               <div class="card">
                  <img class="card-img-top" src="@item.ImageThumbnailUrl" alt="Card image cap">
                  <div class="card-body">
                    <h3 class="card-text"><a asp-controller="Pie" asp-action="Details" asp-route-id="@item.Id" >@item.Name</a></h3>
                    <p class="card-text">@item.Description</p>
                    <p class="card-text"><a asp-controller="ShopingCards" asp-action="Create" asp-route-id="@item.Id" >Add To shoping Cards</a></p>
                  </div>
               </div>
              </div>
        }
 </div>

</div>

Restaurant_DotnetCoreMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant_DotnetCoreMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pie" asp-action="Index">Restaurant_DotnetCoreMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pie" asp-action="Index">Pies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Restaurant_DotnetCoreMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Restaurant_DotnetCoreMvc/Views/ShopingCards/Index.cshtml
@model IQueryable<ShopingCardItem>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<table class="table">
      <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th>Amount</th>
    <th>Actions</th>

  </tr>
@foreach (var item in @Model)
{
  <tr>
        <td>@item.Pie.Name</td>
        <td>@item.Pie.Price</td>
        <td>@item.Pie.Description</td>
        <td>@item.Amount</td>
        <td><a asp-controller="ShopingCards" asp-action="Delete" asp-route-Id="@item.ShopingCardItemId" >Remove from shoping cards</a></td>

  </tr>
}   
</table>